//
//  AppDelegate.m
//  MeanMachine
//
//  Created by John Snow on 4/20/26.
//

#import "AppDelegate.h"

#include "FileIO.hpp"
#include "SBoxTables.hpp"

#include <algorithm>
#include <array>
#include <cstdint>
#include <cstdio>
#include <filesystem>
#include <string>
#include <vector>
#include <unordered_set>


#include "TwistWorkSpace.hpp"
#include "TwistSeeder.hpp"
#include "GStatementRecipe.hpp"
#include "TwistFunctional.hpp"
#include "GTermExpander.hpp"
#include "FastMatrix8.hpp"
#include "Random.hpp"
#include "GSimpleLoopExampleRecipe.hpp"
#include "GSeedStepARecipe.hpp"
#include "GTwistExpander.hpp"

namespace {

std::vector<std::vector<std::uint8_t>> gSBoxTables;
bool gSBoxTablesDidLoad = false;

bool IsRunningUnderXCTest() {
    return (std::getenv("XCTestConfigurationFilePath") != nullptr) ||
    (std::getenv("XCTestBundlePath") != nullptr);
}


}

/*
namespace {

constexpr std::size_t kSBoxLength = 256U;
constexpr std::size_t kMaxExportBoxes = 256U;

std::string MakeBoxSuffix(const std::size_t pIndex) {
    if (pIndex < 26U) {
        return std::string(1, static_cast<char>('A' + static_cast<int>(pIndex)));
    }
    return std::to_string(pIndex + 1U);
}

bool IsPermutationBox(const std::vector<std::uint8_t> &pBox) {
    if (pBox.size() != kSBoxLength) {
        return false;
    }

    std::array<bool, kSBoxLength> aSeen = {};
    for (const std::uint8_t aValue : pBox) {
        if (aSeen[aValue]) {
            return false;
        }
        aSeen[aValue] = true;
    }
    return true;
}

std::vector<std::vector<std::uint8_t>> LoadExportBoxes() {
    
    const std::string aDirectory = FileIO::ProjectRoot("Assets/data_s_box");
    std::vector<std::string> aPaths = FileIO::GetAllFiles(aDirectory);
    std::sort(aPaths.begin(), aPaths.end());
    
    auto aBoxed = SBoxTables::Get();
    

    std::vector<std::vector<std::uint8_t>> aBoxes;
    for (const std::string &aPath : aPaths) {
        std::vector<std::uint8_t> aFileData;
        if (!FileIO::Load(aPath, aFileData)) {
            continue;
        }

        for (std::size_t aOffset = 0U; (aOffset + kSBoxLength) <= aFileData.size(); aOffset += kSBoxLength) {
            std::vector<std::uint8_t> aBox(aFileData.begin() + static_cast<long>(aOffset),
                                           aFileData.begin() + static_cast<long>(aOffset + kSBoxLength));
            if (!IsPermutationBox(aBox)) {
                continue;
            }
            aBoxes.push_back(aBox);
            if (aBoxes.size() >= kMaxExportBoxes) {
                return aBoxes;
            }
        }
    }
    return aBoxes;
}

std::vector<std::uint8_t> BuildInverseBox(const std::vector<std::uint8_t> &pForward) {
    std::vector<std::uint8_t> aReverse(kSBoxLength, 0U);
    for (std::size_t i = 0U; i < pForward.size() && i < kSBoxLength; ++i) {
        aReverse[pForward[i]] = static_cast<std::uint8_t>(i);
    }
    return aReverse;
}

void AppendBoxCode(std::string *pDest,
                   const std::string &pName,
                   const std::vector<std::uint8_t> &pBox) {
    if (pDest == NULL) {
        return;
    }

    *pDest += "unsigned char ";
    *pDest += pName;
    *pDest += "[256] = {\n";

    for (std::size_t i = 0U; i < pBox.size(); ++i) {
        if ((i % 16U) == 0U) {
            *pDest += "    ";
        }

        char aBuffer[8];
        std::snprintf(aBuffer, sizeof(aBuffer), "0x%02X", pBox[i]);
        *pDest += aBuffer;

        if (i + 1U != pBox.size()) {
            *pDest += ", ";
        }

        if ((i % 16U) == 15U) {
            *pDest += "\n";
        }
    }

    if ((pBox.size() % 16U) != 0U) {
        *pDest += "\n";
    }
    *pDest += "};\n\n";
}

std::string BuildExportCode(const std::vector<std::vector<std::uint8_t>> &pBoxes) {
    std::string aCode;
    aCode += "// Generated by MeanMachine/AppDelegate.mm\n";
    aCode += "// First 10 permutation S-boxes from Assets/data_s_box with inverses.\n\n";

    for (std::size_t i = 0U; i < pBoxes.size(); ++i) {
        const std::string aSuffix = MakeBoxSuffix(i);
        const std::vector<std::uint8_t> aReverse = BuildInverseBox(pBoxes[i]);
        AppendBoxCode(&aCode, "mForwardBox" + aSuffix, pBoxes[i]);
        AppendBoxCode(&aCode, "mReverseBox" + aSuffix, aReverse);
    }

    return aCode;
}

void ExportSBoxesAsHeader() {
    const std::vector<std::vector<std::uint8_t>> aBoxes = LoadExportBoxes();
    if (aBoxes.empty()) {
        std::printf("S-box export skipped: no permutation boxes found in Assets/data_s_box.\n");
        return;
    }

    const std::string aCode = BuildExportCode(aBoxes);
    const std::string aOutputPath = FileIO::ProjectRoot("generated/exported_s_boxes.hpp");
    std::vector<std::uint8_t> aBytes(aCode.begin(), aCode.end());
    if (!FileIO::Save(aOutputPath, aBytes)) {
        std::printf("S-box export failed: %s\n", aOutputPath.c_str());
        return;
    }

    std::printf("Exported %zu S-box pairs to %s\n", aBoxes.size(), aOutputPath.c_str());
}

} // namespace
*/

@interface AppDelegate ()

@property (strong) IBOutlet NSWindow *window;
@end

@implementation AppDelegate

- (void)applicationDidFinishLaunching:(NSNotification *)aNotification {
    (void)aNotification;
    
    
    if (IsRunningUnderXCTest()) { return; }
    
    
    std::string aErrorString;
    
    
    GBatch aBatch;
    GSimpleLoopExampleRecipe aRecipeSimple;
    if (!aRecipeSimple.Plan(aErrorString)) {
        printf("{real seeder flow} simple recipe plan failed: %s\n", aErrorString.c_str());
        return;
    }
    
    bool aOrderValue[4];
    bool aOrderCarry[4];
    
    memset(aOrderValue, 0, sizeof(aOrderValue));
    memset(aOrderCarry, 0, sizeof(aOrderValue));
    
    if (!aRecipeSimple.Bake(aBatch.mLoops,
                            aOrderValue,
                            true,
                            aOrderCarry,
                            true,
                            aErrorString)) {
        printf("{real seeder flow} simple recipe bake failed: %s\n", aErrorString.c_str());
        return;
    }
    
    printf("Getting Ready A...\n");
    printf("Getting Ready B...\n");
    
    
    printf("%s\n", aBatch.ToPrettyString().c_str());
    
    printf("So Steady A...\n");
    printf("So Steady B...\n");
    
    
    
    
    
    
    GSeedStepARecipeWorkSpace aRecipeSpace;
    

    GBatch aBatch1;
    if (!aRecipeSpace.Plan(false, aErrorString)) {
        printf("{real seeder flow} stepA pass1 plan failed: %s\n", aErrorString.c_str());
        return;
    }
    
    
   
    if (!aRecipeSpace.Bake(aBatch1.mLoops, aErrorString)) {
        printf("{real seeder flow} stepA pass1 bake failed: %s\n", aErrorString.c_str());
        return;
    }
    
    GBatch aBatch2;
    if (!aRecipeSpace.Plan(true, aErrorString)) {
        printf("{real seeder flow} stepA pass2 plan failed: %s\n", aErrorString.c_str());
        return;
    }
    
    
   
    if (!aRecipeSpace.Bake(aBatch2.mLoops, aErrorString)) {
        printf("{real seeder flow} stepA pass2 bake failed: %s\n", aErrorString.c_str());
        return;
    }
    
    
    printf("ok, the plan worked\n");
    
    printf("%s\n", aBatch1.ToPrettyString().c_str());
    
    printf("ok, the plan worked\n");
    
    printf("%s\n", aBatch2.ToPrettyString().c_str());
    
    printf("ok, the plan worked\n");
    
    
    
    GTwistExpander aExpander;
    
    aExpander.mSeeder.AddBatch(aBatch1);
    aExpander.mSeeder.AddBatch(aBatch2);
    
    aExpander.mSeeder.AddAssignByteLine("aValue", Random::Get(200000000));
    aExpander.mSeeder.AddAssignByteLine("aCarry", Random::Get(200000000));
    aExpander.mSeeder.AddAssignByteLine("aPermute", Random::Get(200000000));
    
    aExpander.mNameBase = "FrodoShire";
    
    if (!aExpander.ExportCPPProjectRoot("CornTesting/Gen", &aErrorString) ||
        !aExpander.ExportJSONProjectRoot("CornTesting/Gen", &aErrorString) ||
        !aExpander.ExportCPPProjectRoot("aaa/bbb/ccc", &aErrorString) ||
        !aExpander.ExportJSONProjectRoot("aaa/bbb/ccc", &aErrorString)) {
        printf("expander export failed: %s\n", aErrorString.c_str());
        return;
    }
    
    
}


- (void)applicationWillTerminate:(NSNotification *)aNotification {
    (void)aNotification;
}


- (BOOL)applicationSupportsSecureRestorableState:(NSApplication *)app {
    return YES;
}


@end
