//
//  AppDelegate.m
//  MeanMachine
//
//  Created by John Snow on 4/20/26.
//

#import "AppDelegate.h"

#include "FileIO.hpp"
#include "SBoxTables.hpp"

#include <algorithm>
#include <array>
#include <cstring>
#include <cstdint>
#include <cstdio>
#include <filesystem>
#include <string>
#include <vector>
#include <unordered_set>
#include "TwistWorkSpace.hpp"
#include "TwistFunctional.hpp"
#include "GTermExpander.hpp"
#include "FastMatrix8.hpp"
#include "Random.hpp"
#include "GTwistExpander.hpp"
#include "TwistCryptoScoring.hpp"
#include "TwistCryptoGenerator.hpp"
#include "GSeedWorkerBuilder.hpp"
#include "GSeedDeriveMaterial.hpp"

namespace {

std::vector<std::vector<std::uint8_t>> gSBoxTables;
bool gSBoxTablesDidLoad = false;

bool IsRunningUnderXCTest() {
    return (std::getenv("XCTestConfigurationFilePath") != nullptr) ||
    (std::getenv("XCTestBundlePath") != nullptr);
}

}

void TwistWorkSpaceBindExternalBuffers(std::uint8_t *pSource,
                                       std::uint8_t *pDest);

/*
namespace {

constexpr std::size_t kSBoxLength = 256U;
constexpr std::size_t kMaxExportBoxes = 256U;

std::string MakeBoxSuffix(const std::size_t pIndex) {
    if (pIndex < 26U) {
        return std::string(1, static_cast<char>('A' + static_cast<int>(pIndex)));
    }
    return std::to_string(pIndex + 1U);
}

bool IsPermutationBox(const std::vector<std::uint8_t> &pBox) {
    if (pBox.size() != kSBoxLength) {
        return false;
    }

    std::array<bool, kSBoxLength> aSeen = {};
    for (const std::uint8_t aValue : pBox) {
        if (aSeen[aValue]) {
            return false;
        }
        aSeen[aValue] = true;
    }
    return true;
}

std::vector<std::vector<std::uint8_t>> LoadExportBoxes() {
    
    const std::string aDirectory = FileIO::ProjectRoot("Assets/data_s_box");
    std::vector<std::string> aPaths = FileIO::GetAllFiles(aDirectory);
    std::sort(aPaths.begin(), aPaths.end());
    
    auto aBoxed = SBoxTables::Get();
    

    std::vector<std::vector<std::uint8_t>> aBoxes;
    for (const std::string &aPath : aPaths) {
        std::vector<std::uint8_t> aFileData;
        if (!FileIO::Load(aPath, aFileData)) {
            continue;
        }

        for (std::size_t aOffset = 0U; (aOffset + kSBoxLength) <= aFileData.size(); aOffset += kSBoxLength) {
            std::vector<std::uint8_t> aBox(aFileData.begin() + static_cast<long>(aOffset),
                                           aFileData.begin() + static_cast<long>(aOffset + kSBoxLength));
            if (!IsPermutationBox(aBox)) {
                continue;
            }
            aBoxes.push_back(aBox);
            if (aBoxes.size() >= kMaxExportBoxes) {
                return aBoxes;
            }
        }
    }
    return aBoxes;
}

std::vector<std::uint8_t> BuildInverseBox(const std::vector<std::uint8_t> &pForward) {
    std::vector<std::uint8_t> aReverse(kSBoxLength, 0U);
    for (std::size_t i = 0U; i < pForward.size() && i < kSBoxLength; ++i) {
        aReverse[pForward[i]] = static_cast<std::uint8_t>(i);
    }
    return aReverse;
}

void AppendBoxCode(std::string *pDest,
                   const std::string &pName,
                   const std::vector<std::uint8_t> &pBox) {
    if (pDest == NULL) {
        return;
    }

    *pDest += "unsigned char ";
    *pDest += pName;
    *pDest += "[256] = {\n";

    for (std::size_t i = 0U; i < pBox.size(); ++i) {
        if ((i % 16U) == 0U) {
            *pDest += "    ";
        }

        char aBuffer[8];
        std::snprintf(aBuffer, sizeof(aBuffer), "0x%02X", pBox[i]);
        *pDest += aBuffer;

        if (i + 1U != pBox.size()) {
            *pDest += ", ";
        }

        if ((i % 16U) == 15U) {
            *pDest += "\n";
        }
    }

    if ((pBox.size() % 16U) != 0U) {
        *pDest += "\n";
    }
    *pDest += "};\n\n";
}

std::string BuildExportCode(const std::vector<std::vector<std::uint8_t>> &pBoxes) {
    std::string aCode;
    aCode += "// Generated by MeanMachine/AppDelegate.mm\n";
    aCode += "// First 10 permutation S-boxes from Assets/data_s_box with inverses.\n\n";

    for (std::size_t i = 0U; i < pBoxes.size(); ++i) {
        const std::string aSuffix = MakeBoxSuffix(i);
        const std::vector<std::uint8_t> aReverse = BuildInverseBox(pBoxes[i]);
        AppendBoxCode(&aCode, "mForwardBox" + aSuffix, pBoxes[i]);
        AppendBoxCode(&aCode, "mReverseBox" + aSuffix, aReverse);
    }

    return aCode;
}

void ExportSBoxesAsHeader() {
    const std::vector<std::vector<std::uint8_t>> aBoxes = LoadExportBoxes();
    if (aBoxes.empty()) {
        std::printf("S-box export skipped: no permutation boxes found in Assets/data_s_box.\n");
        return;
    }

    const std::string aCode = BuildExportCode(aBoxes);
    const std::string aOutputPath = FileIO::ProjectRoot("generated/exported_s_boxes.hpp");
    std::vector<std::uint8_t> aBytes(aCode.begin(), aCode.end());
    if (!FileIO::Save(aOutputPath, aBytes)) {
        std::printf("S-box export failed: %s\n", aOutputPath.c_str());
        return;
    }

    std::printf("Exported %zu S-box pairs to %s\n", aBoxes.size(), aOutputPath.c_str());
}

} // namespace
*/

@interface AppDelegate ()

@property (strong) IBOutlet NSWindow *window;
@end

@implementation AppDelegate

- (void)applicationDidFinishLaunching:(NSNotification *)aNotification {
    (void)aNotification;
    
    TwistCryptoGenerator aGen;
    TwistCryptoScoring aAnalyzer;

    std::uint8_t aSource[S_BLOCK];
    for (int i=0;i<S_BLOCK;i++) {
        aSource[i] = Random::Get(256);
    }
    
    std::uint8_t aBox1[256];
    std::uint8_t aBox2[256];
    std::uint8_t aBox3[256];
    std::uint8_t aBox4[256];
    aGen.Make(aSource, aBox1, aBox2, aBox3, aBox4);
    
    std::uint8_t aSalt1[128];
    std::uint8_t aSalt2[128];
    std::uint8_t aSalt3[128];
    std::uint8_t aSalt4[128];
    
    aGen.Salt(aSource,
              aSalt1,
              aSalt2,
              aSalt3,
              aSalt4,
              aBox1,
              aBox2,
              aBox3,
              aBox4);
    
    std::uint8_t aBox5[256];
    std::uint8_t aBox6[256];
    std::uint8_t aBox7[256];
    std::uint8_t aBox8[256];
    aGen.Make(aSource, aBox5, aBox6, aBox7, aBox8);
    
    std::uint8_t aSalt5[128];
    std::uint8_t aSalt6[128];
    std::uint8_t aSalt7[128];
    std::uint8_t aSalt8[128];
    
    aGen.Salt(aSource,
              aSalt5,
              aSalt6,
              aSalt7,
              aSalt8,
              aSalt1,
              aSalt2,
              aSalt3,
              aSalt4,
              aBox1,
              aBox2,
              aBox3,
              aBox4,
              aBox5,
              aBox6,
              aBox7,
              aBox8);
    printf("slow crunch... done\n");
    
    
    /*
    TwistCryptoGenerator aGen;
     TwistCryptoScoring aAnalyzer;

    std::uint8_t aSource[S_BLOCK];
    for (int i=0;i<S_BLOCK;i++) {
        aSource[i] = Random::Get(256);
    }

    
    std::uint8_t aBox1[256];
    std::uint8_t aBox2[256];
    std::uint8_t aBox3[256];
    std::uint8_t aBox4[256];
    

    aGen.Make(aSource, aBox1, aBox2, aBox3, aBox4);
    
    
    std::uint8_t aBox5[256];
    std::uint8_t aBox6[256];
    std::uint8_t aBox7[256];
    std::uint8_t aBox8[256];
    
    aGen.Make(aSource,
              aBox5, aBox6, aBox7, aBox8,
              aBox1, aBox2, aBox3, aBox4);
    
    printf("\n================ S-BOX SET 1 ================\n");

    aAnalyzer.PrintBox_256("Box1", aBox1);
    aAnalyzer.PrintBox_256("Box2", aBox2);
    aAnalyzer.PrintBox_256("Box3", aBox3);
    aAnalyzer.PrintBox_256("Box4", aBox4);

    printf("\n================ S-BOX SET 2 ================\n");

    aAnalyzer.PrintBox_256("Box5", aBox5);
    aAnalyzer.PrintBox_256("Box6", aBox6);
    aAnalyzer.PrintBox_256("Box7", aBox7);
    aAnalyzer.PrintBox_256("Box8", aBox8);

    printf("\n=============================================\n");

    printf("\n=============================================\n");
    printf("\n=============================================\n");
    */
    
    /*
    
    std::vector<std::uint8_t *> aList;
    aList.push_back(aBox1);
    aList.push_back(aBox2);
    aList.push_back(aBox3);
    aList.push_back(aBox4);
    
    for (int aBox=0;aBox<aList.size();aBox++) {
        
        std::uint8_t *aData = aList[aBox];
        int aLength = 256;
        
        int aDDTMax = aAnalyzer.ComputeDifferenceDistributionTableMax_256(aByteString.mData, aByteString.mLength);
        int aWalsh = aAnalyzer.ComputeLinearCorrelationMax_256(aByteString.mData, aByteString.mLength);
        int aMinComponentDegree = aAnalyzer.ComputeMinimumComponentAlgebraicDegree_256(aByteString.mData, aByteString.mLength);
        int aMaxComponentDegree = aAnalyzer.ComputeMaximumComponentAlgebraicDegree_256(aByteString.mData, aByteString.mLength);
        int aSacMaxBias = aAnalyzer.ComputeSacMaxBias_256(aByteString.mData, aByteString.mLength);
        float aSacAverageBias = aAnalyzer.ComputeSacAverageBias_256(aByteString.mData, aByteString.mLength);
        int aBicMaxBias = aAnalyzer.ComputeBicMaxBias_256(aByteString.mData, aByteString.mLength);
        float aBicAverageBias = aAnalyzer.ComputeBicAverageBias_256(aByteString.mData, aByteString.mLength);
        
        printf("Final Box %d (%d %d) [%d + %d] (%f| %d) [%f| %d]\n", aBox,
               aDDTMax, aWalsh,
               aMinComponentDegree, aMaxComponentDegree,
               aSacAverageBias, aSacMaxBias,
               aBicAverageBias, aBicMaxBias);
        
    }
    
    */
     
    /*
    
    SBoxMaterial aMaterial;

    std::vector<std::vector<std::uint8_t>> aSBoxes = SBoxTables::Get();

    auto aListOfBoxes = SBoxTables::Get();

    int aChunksDone = 0;
    for (auto &aSBox: aListOfBoxes) {
        
        
        ByteString aByteString(aSBox);
        int aDDTMax = aAnalyzer.ComputeDifferenceDistributionTableMax_256(aByteString.mData, aByteString.mLength);
        int aWalsh = aAnalyzer.ComputeLinearCorrelationMax_256(aByteString.mData, aByteString.mLength);
        int aMinComponentDegree = aAnalyzer.ComputeMinimumComponentAlgebraicDegree_256(aByteString.mData, aByteString.mLength);
        int aMaxComponentDegree = aAnalyzer.ComputeMaximumComponentAlgebraicDegree_256(aByteString.mData, aByteString.mLength);
        int aSacMaxBias = aAnalyzer.ComputeSacMaxBias_256(aByteString.mData, aByteString.mLength);
        double aSacAverageBias = aAnalyzer.ComputeSacAverageBias_256(aByteString.mData, aByteString.mLength);
        int aBicMaxBias = aAnalyzer.ComputeBicMaxBias_256(aByteString.mData, aByteString.mLength);
        double aBicAverageBias = aAnalyzer.ComputeBicAverageBias_256(aByteString.mData, aByteString.mLength);
        
        aChunksDone++;
        
        if (aDDTMax <= 4) {
            if (aWalsh <= 32) {
                
                if (aSacAverageBias <= 5.20) {
                    if (aSacMaxBias <= 16) {
                        
                        if (aBicAverageBias <= 6.35) {
                            
                            if (aBicMaxBias <= 16) {
                                
                                // print first 16 entries as hex
                                printf("SBox[%02d] head: ", aChunksDone);
                                for (int k = 0; k < 16 && k < (int)aSBox.size(); k++) {
                                    printf("%02X ", aByteString.mData[k]);
                                }
                                printf("\n");
                                
                                printf("done with chunk %d\n", (int)aChunksDone);
                                printf("aSacAverageBias gate passed, %f\n", aSacAverageBias);
                                printf("aBicAverageBias gate passed, %f\n", aBicAverageBias);
                                printf("aSacMaxBias gate passed, %d\n", aSacMaxBias);
                                printf("aBicMaxBias gate passed, %d\n", aBicMaxBias);
                                printf("-----\n");
                                
                                //aMaterial.AddPasser(aByteString);
                            }
                        }
                    }
                }
            }
        }
    }
    
    */
    
    
    
    if (IsRunningUnderXCTest()) { return; }
    

    
    
    /*
    
    std::string aError;
    GSeedWorkerBuilder aSeedWorkerBuilder;
    TwistProgramBranch aSeedBranch;

    if (!aSeedWorkerBuilder.BuildPhaseA(aSeedBranch, aError)) {
        printf("error on GSeedWorkerBuilder\n");
        printf("%s\n", aError.c_str());
        return;
    }

    printf("\n===== Seed Branch (C++) =====\n");
    const std::vector<TwistProgramBranchStep> &aSteps = aSeedBranch.GetSteps();
    if (aSteps.empty()) {
        for (const std::string &aLine : aSeedBranch.GetStringLines()) {
            printf("%s\n", aLine.c_str());
        }
        for (const std::string &aBatchJson : aSeedBranch.GetBatchJsonText()) {
            GBatch aBatch;
            std::string aBatchError;
            if (!GBatch::FromJson(aBatchJson, &aBatch, &aBatchError)) {
                printf("error parsing seed branch batch JSON\n");
                printf("%s\n", aBatchError.c_str());
                return;
            }
            const std::string aScopeText = aBatch.BuildCppScopeBlock(&aBatchError, false);
            if (aScopeText.empty()) {
                printf("error generating seed branch C++ scope block\n");
                printf("%s\n", aBatchError.c_str());
                return;
            }
            printf("%s\n", aScopeText.c_str());
        }
    } else {
        for (const TwistProgramBranchStep &aStep : aSteps) {
            if (aStep.mType == TwistProgramBranchStepType::kLine) {
                if (aStep.mIndex >= aSeedBranch.GetStringLines().size()) {
                    printf("error: seed branch line step index out of range\n");
                    return;
                }
                printf("%s\n", aSeedBranch.GetStringLines()[aStep.mIndex].c_str());
                continue;
            }

            if (aStep.mType == TwistProgramBranchStepType::kBatch) {
                if (aStep.mIndex >= aSeedBranch.GetBatchJsonText().size()) {
                    printf("error: seed branch batch step index out of range\n");
                    return;
                }

                GBatch aBatch;
                std::string aBatchError;
                if (!GBatch::FromJson(aSeedBranch.GetBatchJsonText()[aStep.mIndex], &aBatch, &aBatchError)) {
                    printf("error parsing seed branch batch JSON\n");
                    printf("%s\n", aBatchError.c_str());
                    return;
                }
                const std::string aScopeText = aBatch.BuildCppScopeBlock(&aBatchError, false);
                if (aScopeText.empty()) {
                    printf("error generating seed branch C++ scope block\n");
                    printf("%s\n", aBatchError.c_str());
                    return;
                }
                printf("%s\n", aScopeText.c_str());
                continue;
            }

            printf("error: invalid seed branch step type\n");
            return;
        }
    }
    printf("===== End Seed Branch =====\n\n");

    std::uint8_t aSource[S_BLOCK];
    for (int aIndex = 0; aIndex < S_BLOCK; aIndex++) {
        aSource[aIndex] = static_cast<std::uint8_t>(Random::Get(256));
    }

    TwistWorkSpace aWorkspace;
    std::memcpy(aWorkspace.mExpandLaneA, aSource, static_cast<std::size_t>(S_BLOCK));
    TwistWorkSpaceBindExternalBuffers(aSource, nullptr);

    if (!aSeedWorkerBuilder.ExecuteBranch(&aWorkspace, aSeedBranch, aError)) {
        printf("error on ExecuteBranch\n");
        printf("%s\n", aError.c_str());
        return;
    }

    printf("GSeedWorkerBuilder demo completed.\n");
    
    */
    
    
    
    //aWBWB.BuildPhaseA(aSeedBranch, <#std::string &pError#>)
    
    GSeedDeriveMaterial aDer;
    std::string aError;
    GTwistExpander aExpander;
    
    if (!aDer.PlanPhaseA(aError)) {
        printf("error on GSeedDeriveMaterial.PlanPhaseA\n");
        printf("%s\n", aError.c_str());
        return;
    }
    
    if (!aDer.BuildPhaseA(aExpander.mSeeder, aError)) {
        printf("error on GSeedDeriveMaterial.BuildPhaseA\n");
        printf("%s\n", aError.c_str());
        return;
    }
    
    if (//!aExpander.ExportCPPProjectRoot("CornTesting/Gen", &aError) ||
        //!aExpander.ExportJSONProjectRoot("CornTesting/Gen", &aError) ||
        !aExpander.ExportCPPProjectRoot("aaa/bbb/ccc", &aError) ||
        !aExpander.ExportJSONProjectRoot("aaa/bbb/ccc", &aError)) {
        printf("expander export failed: %s\n", aError.c_str());
        return;
    }
    
    printf("process finished\n");
    
    /*
    if (!aSeedWorkerBuilder.BuildPhaseA(aSeedBranch, aError)) {
        
    }
    
    
    if (!aRecipeSpace.Plan(false, aErrorString)) {
        printf("{real seeder flow} stepA pass1 plan failed: %s\n", aErrorString.c_str());
        return;
    }
    
    
   
    if (!aRecipeSpace.Bake(aBatch1.mLoops, aErrorString)) {
        printf("{real seeder flow} stepA pass1 bake failed: %s\n", aErrorString.c_str());
        return;
    }
    
    GBatch aBatch2;
    if (!aRecipeSpace.Plan(true, aErrorString)) {
        printf("{real seeder flow} stepA pass2 plan failed: %s\n", aErrorString.c_str());
        return;
    }
    
    
   
    if (!aRecipeSpace.Bake(aBatch2.mLoops, aErrorString)) {
        printf("{real seeder flow} stepA pass2 bake failed: %s\n", aErrorString.c_str());
        return;
    }
    
    
    printf("ok, the plan worked\n");
    
    printf("%s\n", aBatch1.ToPrettyString().c_str());
    
    printf("ok, the plan worked\n");
    
    printf("%s\n", aBatch2.ToPrettyString().c_str());
    
    printf("ok, the plan worked\n");
    
    
    
    GTwistExpander aExpander;
    
    aExpander.mSeeder.AddBatch(aBatch1);
    aExpander.mSeeder.AddBatch(aBatch2);
    
    aExpander.mSeeder.AddAssignByteLine("aValue", Random::Get(200000000));
    aExpander.mSeeder.AddAssignByteLine("aCarry", Random::Get(200000000));
    aExpander.mSeeder.AddAssignByteLine("aPermute", Random::Get(200000000));
    
    aExpander.mNameBase = "Froyo";
    
    if (!aExpander.ExportCPPProjectRoot("CornTesting/Gen", &aErrorString) ||
        !aExpander.ExportJSONProjectRoot("CornTesting/Gen", &aErrorString) ||
        !aExpander.ExportCPPProjectRoot("aaa/bbb/ccc", &aErrorString) ||
        !aExpander.ExportJSONProjectRoot("aaa/bbb/ccc", &aErrorString)) {
        printf("expander export failed: %s\n", aErrorString.c_str());
        return;
    }
    
    */
    
}


- (void)applicationWillTerminate:(NSNotification *)aNotification {
    (void)aNotification;
}


- (BOOL)applicationSupportsSecureRestorableState:(NSApplication *)app {
    return YES;
}


@end
