//
//  AppDelegate.m
//  MeanMachine
//
//  Created by John Snow on 4/20/26.
//

#import "AppDelegate.h"

#include "FileIO.hpp"
#include "SBoxTables.hpp"

#include <algorithm>
#include <array>
#include <cstdint>
#include <cstdio>
#include <filesystem>
#include <string>
#include <vector>
#include <unordered_set>


#include "TwistWorkSpace.hpp"
#include "TwistSeeder.hpp"
#include "GStatementRecipe.hpp"
#include "TwistFunctional.hpp"
#include "GTermExpander.hpp"
#include "FastMatrix8.hpp"
#include "Random.hpp"
#include "GSimpleLoopExampleRecipe.hpp"
#include "GSeedStepARecipe.hpp"
#include "GTwistExpander.hpp"
#include "SBoxAnalyzer.hpp"
#include "SBoxMaterial.hpp"
#include "SBoxGenerator.hpp"

namespace {

std::vector<std::vector<std::uint8_t>> gSBoxTables;
bool gSBoxTablesDidLoad = false;

bool IsRunningUnderXCTest() {
    return (std::getenv("XCTestConfigurationFilePath") != nullptr) ||
    (std::getenv("XCTestBundlePath") != nullptr);
}


}

/*
namespace {

constexpr std::size_t kSBoxLength = 256U;
constexpr std::size_t kMaxExportBoxes = 256U;

std::string MakeBoxSuffix(const std::size_t pIndex) {
    if (pIndex < 26U) {
        return std::string(1, static_cast<char>('A' + static_cast<int>(pIndex)));
    }
    return std::to_string(pIndex + 1U);
}

bool IsPermutationBox(const std::vector<std::uint8_t> &pBox) {
    if (pBox.size() != kSBoxLength) {
        return false;
    }

    std::array<bool, kSBoxLength> aSeen = {};
    for (const std::uint8_t aValue : pBox) {
        if (aSeen[aValue]) {
            return false;
        }
        aSeen[aValue] = true;
    }
    return true;
}

std::vector<std::vector<std::uint8_t>> LoadExportBoxes() {
    
    const std::string aDirectory = FileIO::ProjectRoot("Assets/data_s_box");
    std::vector<std::string> aPaths = FileIO::GetAllFiles(aDirectory);
    std::sort(aPaths.begin(), aPaths.end());
    
    auto aBoxed = SBoxTables::Get();
    

    std::vector<std::vector<std::uint8_t>> aBoxes;
    for (const std::string &aPath : aPaths) {
        std::vector<std::uint8_t> aFileData;
        if (!FileIO::Load(aPath, aFileData)) {
            continue;
        }

        for (std::size_t aOffset = 0U; (aOffset + kSBoxLength) <= aFileData.size(); aOffset += kSBoxLength) {
            std::vector<std::uint8_t> aBox(aFileData.begin() + static_cast<long>(aOffset),
                                           aFileData.begin() + static_cast<long>(aOffset + kSBoxLength));
            if (!IsPermutationBox(aBox)) {
                continue;
            }
            aBoxes.push_back(aBox);
            if (aBoxes.size() >= kMaxExportBoxes) {
                return aBoxes;
            }
        }
    }
    return aBoxes;
}

std::vector<std::uint8_t> BuildInverseBox(const std::vector<std::uint8_t> &pForward) {
    std::vector<std::uint8_t> aReverse(kSBoxLength, 0U);
    for (std::size_t i = 0U; i < pForward.size() && i < kSBoxLength; ++i) {
        aReverse[pForward[i]] = static_cast<std::uint8_t>(i);
    }
    return aReverse;
}

void AppendBoxCode(std::string *pDest,
                   const std::string &pName,
                   const std::vector<std::uint8_t> &pBox) {
    if (pDest == NULL) {
        return;
    }

    *pDest += "unsigned char ";
    *pDest += pName;
    *pDest += "[256] = {\n";

    for (std::size_t i = 0U; i < pBox.size(); ++i) {
        if ((i % 16U) == 0U) {
            *pDest += "    ";
        }

        char aBuffer[8];
        std::snprintf(aBuffer, sizeof(aBuffer), "0x%02X", pBox[i]);
        *pDest += aBuffer;

        if (i + 1U != pBox.size()) {
            *pDest += ", ";
        }

        if ((i % 16U) == 15U) {
            *pDest += "\n";
        }
    }

    if ((pBox.size() % 16U) != 0U) {
        *pDest += "\n";
    }
    *pDest += "};\n\n";
}

std::string BuildExportCode(const std::vector<std::vector<std::uint8_t>> &pBoxes) {
    std::string aCode;
    aCode += "// Generated by MeanMachine/AppDelegate.mm\n";
    aCode += "// First 10 permutation S-boxes from Assets/data_s_box with inverses.\n\n";

    for (std::size_t i = 0U; i < pBoxes.size(); ++i) {
        const std::string aSuffix = MakeBoxSuffix(i);
        const std::vector<std::uint8_t> aReverse = BuildInverseBox(pBoxes[i]);
        AppendBoxCode(&aCode, "mForwardBox" + aSuffix, pBoxes[i]);
        AppendBoxCode(&aCode, "mReverseBox" + aSuffix, aReverse);
    }

    return aCode;
}

void ExportSBoxesAsHeader() {
    const std::vector<std::vector<std::uint8_t>> aBoxes = LoadExportBoxes();
    if (aBoxes.empty()) {
        std::printf("S-box export skipped: no permutation boxes found in Assets/data_s_box.\n");
        return;
    }

    const std::string aCode = BuildExportCode(aBoxes);
    const std::string aOutputPath = FileIO::ProjectRoot("generated/exported_s_boxes.hpp");
    std::vector<std::uint8_t> aBytes(aCode.begin(), aCode.end());
    if (!FileIO::Save(aOutputPath, aBytes)) {
        std::printf("S-box export failed: %s\n", aOutputPath.c_str());
        return;
    }

    std::printf("Exported %zu S-box pairs to %s\n", aBoxes.size(), aOutputPath.c_str());
}

} // namespace
*/

@interface AppDelegate ()

@property (strong) IBOutlet NSWindow *window;
@end

@implementation AppDelegate

- (void)applicationDidFinishLaunching:(NSNotification *)aNotification {
    (void)aNotification;
    
    /*
    SBoxGenerator aGen;
     SBoxAnalyzer aAnalyzer;

    std::uint8_t aSource[S_BLOCK];
    for (int i=0;i<S_BLOCK;i++) {
        aSource[i] = Random::Get(256);
    }

    ByteString aBoxA; aBoxA.Size(256); aBoxA.mLength = 256;
    ByteString aBoxB; aBoxB.Size(256); aBoxB.mLength = 256;
    ByteString aBoxC; aBoxC.Size(256); aBoxC.mLength = 256;
    ByteString aBoxD; aBoxD.Size(256); aBoxD.mLength = 256;


    aGen.Make(aSource, aBoxA.mData, aBoxB.mData, aBoxC.mData, aBoxD.mData);

    ByteString aTest;
    aTest.Size(256);

    

    std::vector<ByteString> aList;
    aList.push_back(aBoxA);
    aList.push_back(aBoxB);
    aList.push_back(aBoxC);
    aList.push_back(aBoxD);
    for (int aBox=0;aBox<aList.size();aBox++) {
        
        aTest.Set(aList[aBox].mData, 256);
        
        int aDDTMax = aAnalyzer.ComputeDifferenceDistributionTableMax_256(aTest.mData, aTest.mLength);
        int aWalsh = aAnalyzer.ComputeLinearCorrelationMax_256(aTest.mData, aTest.mLength);
        int aMinComponentDegree = aAnalyzer.ComputeMinimumComponentAlgebraicDegree_256(aTest.mData, aTest.mLength);
        int aMaxComponentDegree = aAnalyzer.ComputeMaximumComponentAlgebraicDegree_256(aTest.mData, aTest.mLength);
        int aSacMaxBias = aAnalyzer.ComputeSacMaxBias_256(aTest.mData, aTest.mLength);
        double aSacAverageBias = aAnalyzer.ComputeSacAverageBias_256(aTest.mData, aTest.mLength);
        int aBicMaxBias = aAnalyzer.ComputeBicMaxBias_256(aTest.mData, aTest.mLength);
        double aBicAverageBias = aAnalyzer.ComputeBicAverageBias_256(aTest.mData, aTest.mLength);
        
        
        
        printf("Hex Head %d: ", aBox);
        for (int k = 0; k < 16; k++) {
            printf("%02X ", aList[aBox].mData[k]);
        }
        printf("\n");
        
        printf("Final Box %d [%d, %d] (%d %d) (%f %d) [%f %d]\n", aBox,
               aDDTMax, aWalsh, aMaxComponentDegree, aMinComponentDegree, aSacAverageBias, aSacMaxBias, aBicAverageBias, aBicMaxBias);
        
        
    }
    */
     
    /*
    SBoxMaterial aMaterial;
    SBoxAnalyzer aAnalyzer;

    std::vector<std::vector<std::uint8_t>> aSBoxes = SBoxTables::Get();

    auto aListOfBoxes = SBoxTables::Get();

    int aChunksDone = 0;
    for (auto &aSBox: aListOfBoxes) {
        
        
        ByteString aByteString(aSBox);
        int aDDTMax = aAnalyzer.ComputeDifferenceDistributionTableMax_256(aByteString.mData, aByteString.mLength);
        int aWalsh = aAnalyzer.ComputeLinearCorrelationMax_256(aByteString.mData, aByteString.mLength);
        int aMinComponentDegree = aAnalyzer.ComputeMinimumComponentAlgebraicDegree_256(aByteString.mData, aByteString.mLength);
        int aMaxComponentDegree = aAnalyzer.ComputeMaximumComponentAlgebraicDegree_256(aByteString.mData, aByteString.mLength);
        int aSacMaxBias = aAnalyzer.ComputeSacMaxBias_256(aByteString.mData, aByteString.mLength);
        double aSacAverageBias = aAnalyzer.ComputeSacAverageBias_256(aByteString.mData, aByteString.mLength);
        int aBicMaxBias = aAnalyzer.ComputeBicMaxBias_256(aByteString.mData, aByteString.mLength);
        double aBicAverageBias = aAnalyzer.ComputeBicAverageBias_256(aByteString.mData, aByteString.mLength);

        aChunksDone++;

        if (aDDTMax <= 4) {
            if (aWalsh <= 32) {
            
                if (aSacAverageBias <= 5.20) {
                    if (aSacMaxBias <= 16) {
                        
                        if (aBicAverageBias <= 6.35) {
                            
                            if (aBicMaxBias <= 16) {
                                
                                // print first 16 entries as hex
                                printf("SBox[%02d] head: ", aChunksDone);
                                for (int k = 0; k < 16 && k < (int)aSBox.size(); k++) {
                                    printf("%02X ", aByteString.mData[k]);
                                }
                                printf("\n");
                                
                                printf("done with chunk %d\n", (int)aChunksDone);
                                printf("aSacAverageBias gate passed, %f\n", aSacAverageBias);
                                printf("aBicAverageBias gate passed, %f\n", aBicAverageBias);
                                printf("aSacMaxBias gate passed, %d\n", aSacMaxBias);
                                printf("aBicMaxBias gate passed, %d\n", aBicMaxBias);
                                printf("-----\n");
                                
                                //aMaterial.AddPasser(aByteString);
                            }
                        }
                    }
                }
            }
        }

        }
    */
    
    
    if (IsRunningUnderXCTest()) { return; }
    
    
    std::string aErrorString;
    
    
    GBatch aBatch;
    GSimpleLoopExampleRecipe aRecipeSimple;
    if (!aRecipeSimple.Plan(aErrorString)) {
        printf("{real seeder flow} simple recipe plan failed: %s\n", aErrorString.c_str());
        return;
    }
    
    bool aOrderValue[4];
    bool aOrderCarry[4];
    
    memset(aOrderValue, 0, sizeof(aOrderValue));
    memset(aOrderCarry, 0, sizeof(aOrderValue));
    
    if (!aRecipeSimple.Bake(aBatch.mLoops,
                            aOrderValue,
                            true,
                            aOrderCarry,
                            true,
                            aErrorString)) {
        printf("{real seeder flow} simple recipe bake failed: %s\n", aErrorString.c_str());
        return;
    }
    
    printf("Getting Ready A...\n");
    printf("Getting Ready B...\n");
    
    
    printf("%s\n", aBatch.ToPrettyString().c_str());
    
    printf("So Steady A...\n");
    printf("So Steady B...\n");
    
    
    
    
    
    
    GSeedStepARecipeWorkSpace aRecipeSpace;
    

    GBatch aBatch1;
    if (!aRecipeSpace.Plan(false, aErrorString)) {
        printf("{real seeder flow} stepA pass1 plan failed: %s\n", aErrorString.c_str());
        return;
    }
    
    
   
    if (!aRecipeSpace.Bake(aBatch1.mLoops, aErrorString)) {
        printf("{real seeder flow} stepA pass1 bake failed: %s\n", aErrorString.c_str());
        return;
    }
    
    GBatch aBatch2;
    if (!aRecipeSpace.Plan(true, aErrorString)) {
        printf("{real seeder flow} stepA pass2 plan failed: %s\n", aErrorString.c_str());
        return;
    }
    
    
   
    if (!aRecipeSpace.Bake(aBatch2.mLoops, aErrorString)) {
        printf("{real seeder flow} stepA pass2 bake failed: %s\n", aErrorString.c_str());
        return;
    }
    
    
    printf("ok, the plan worked\n");
    
    printf("%s\n", aBatch1.ToPrettyString().c_str());
    
    printf("ok, the plan worked\n");
    
    printf("%s\n", aBatch2.ToPrettyString().c_str());
    
    printf("ok, the plan worked\n");
    
    
    
    GTwistExpander aExpander;
    
    aExpander.mSeeder.AddBatch(aBatch1);
    aExpander.mSeeder.AddBatch(aBatch2);
    
    aExpander.mSeeder.AddAssignByteLine("aValue", Random::Get(200000000));
    aExpander.mSeeder.AddAssignByteLine("aCarry", Random::Get(200000000));
    aExpander.mSeeder.AddAssignByteLine("aPermute", Random::Get(200000000));
    
    aExpander.mNameBase = "Froyo";
    
    if (!aExpander.ExportCPPProjectRoot("CornTesting/Gen", &aErrorString) ||
        !aExpander.ExportJSONProjectRoot("CornTesting/Gen", &aErrorString) ||
        !aExpander.ExportCPPProjectRoot("aaa/bbb/ccc", &aErrorString) ||
        !aExpander.ExportJSONProjectRoot("aaa/bbb/ccc", &aErrorString)) {
        printf("expander export failed: %s\n", aErrorString.c_str());
        return;
    }
    
    
}


- (void)applicationWillTerminate:(NSNotification *)aNotification {
    (void)aNotification;
}


- (BOOL)applicationSupportsSecureRestorableState:(NSApplication *)app {
    return YES;
}


@end
