//
//  TwistDomains.hpp
//  MeanMachine
//
//  Created by Xenegos of the Revel on 5/7/26.
//

#ifndef TwistDomains_hpp
#define TwistDomains_hpp

#include <cstdint>

/*

Derive(root, WandererDomain, 0) -> wanderer salt 0
Derive(root, WandererDomain, 1) -> wanderer salt 1
Derive(root, OrbiterDomain, 0)  -> orbiter salt 0
Derive(root, KeyBoxDomain, 0)   -> key_box_a
Derive(root, KeyBoxDomain, 1)   -> key_box_b
Derive(root, MaskBoxDomain, 0)  -> mask_box_a
Derive(root, SBoxDomain, 0)     -> sbox seed 0

*/


/*

1. key_box_a
2. key_box_b
3. mask_box_a
4. mask_box_b
5. wanderer salts
6. orbiter salts
7. prism salts
8. carry salts
9. generic s-boxes

you want each one to have these properties:
unique domain label
unique output index / instance id
fixed requested length
derived through a one-way PRF/KDF
not reused as input to a sibling domain without re-extraction
not generated by taking visible adjacent slices from one raw stream

key_box_a  = KDF(root, "key_box_a",  length)
key_box_b  = KDF(root, "key_box_b",  length)
mask_box_a = KDF(root, "mask_box_a", length)
mask_box_b = KDF(root, "mask_box_b", length)
sbox_0     = KDF(root, "sbox", index = 0, length)
sbox_1     = KDF(root, "sbox", index = 1, length)

Derive(
 output,
 output_len,
 root_key,
 TwistSaltDomain::kKeyBoxes,
 instance_index
);

Derive(
 output,
 output_len,
 root_key,
 TwistSaltDomain::kMaskBoxes,
 instance_index
);

Derive(
 output,
 output_len,
 root_key,
 TwistSaltDomain::kCSPRNG_Wanderera,
 salt_index
);

*/

enum class TwistDomain : std::uint8_t {
    kInv = 0,

    // Legacy coarse domains (kept for compatibility).
    kSalts = 1,
    kSBoxes = 2,
    kKeyBoxA = 3,
    kKeyBoxB = 4,
    kMaskBoxA = 5,
    kMaskBoxB = 6,

    // Fine-grained salt domains.
    kSaltsKeyAWanderer = 10,
    kSaltsKeyAOrbiter = 11,
    kSaltsKeyASeeder = 12,

    kSaltsKeyBWanderer = 13,
    kSaltsKeyBOrbiter = 14,
    kSaltsKeyBSeeder = 15,

    kSaltsMaskAWanderer = 16,
    kSaltsMaskAOrbiter = 17,
    kSaltsMaskASeeder = 18,

    kSaltsMaskBWanderer = 19,
    kSaltsMaskBOrbiter = 20,
    kSaltsMaskBSeeder = 21,

    kSaltsWorkLaneWanderer = 22,
    kSaltsWorkLaneOrbiter = 23,
    kSaltsWorkLaneSeeder = 24,

    kSaltsMaskLaneWanderer = 25,
    kSaltsMaskLaneOrbiter = 26,
    kSaltsMaskLaneSeeder = 27,

    kSaltsOperationLaneWanderer = 28,
    kSaltsOperationLaneOrbiter = 29,
    kSaltsOperationLaneSeeder = 30,

    // Fine-grained s-box domains.
    kSBoxesKeyA = 40,
    kSBoxesKeyB = 41,
    kSBoxesMaskA = 42,
    kSBoxesMaskB = 43,
    kSBoxesWorkLane = 44,
    kSBoxesMaskLane = 45,
    kSBoxesOperationLane = 46
};

enum class TwistSaltDomain : std::uint8_t {
    kInv = 0,
    
    kCSPRNG_Wanderera = 1,
    kCSPRNG_Orbitera = 2,
    kCSPRNG_Prisms = 3,
    kCSPRNG_Carries = 4,
    
    kSources = 10,
    kWorkLanes = 20,
    kExpansionLanes = 25,
    
    kMaskLanes = 30,
    kOperationLanes = 35,
    
    kKeyBoxes = 100,
    kMaskBoxes = 120
};

class TwistDomains {
    
    static constexpr unsigned char cDomainUnknown[33] = "unknowm.com.peanutbutter.domains";
    static constexpr unsigned char cDomainMaskkWanderers[33] = "com.peanutbutter.csprng.wandeers";
    static constexpr unsigned char cDomainMaskOrbiters[33] = "org.butterpeanut.csprng.orbiters";
    static constexpr unsigned char cDomainMaskPrisms[33] = "org.butterpeanut.csprng.selected";
    static constexpr unsigned char cDomainMaskCarries[33] = "net.butterpeanut.csprng.carrying";
    
    static constexpr unsigned char cDomainMaskSources[33] = "net.butterpeanut.buffers.sources";
    static constexpr unsigned char cDomainMaskWorkLanes[33] = "net.butterpeanut.buffers.workers";
    static constexpr unsigned char cDomainMaskExpansionLanes[33] = "net.butterpeanut.buffers.expands";
    static constexpr unsigned char cDomainMaskMaskLanes[33] = "net.butterpeanut.buffers.masking";
    static constexpr unsigned char cDomainMaskOperationLanes[33] = "net.butterpeanut.buffers.operate";
    
    static constexpr unsigned char cDomainMaskKeyBoxes[33] = "net.butterpeanut.boxes.keys.main";
    static constexpr unsigned char cDomainMaskMaskBoxes[33] = "net.butterpeanut.boxes.masks.all";
    
    static constexpr const unsigned char *GetDomainMask(TwistSaltDomain pDomain);
    
    
    
};


#endif /* TwistDomains_hpp */
