from __future__ import annotations

from pathlib import Path

from byte_flow_image import (
    DEFAULT_OUTPUT_ROOT as DEFAULT_BYTE_FLOW_IMAGE_ROOT,
    make_byte_flow_image,
    output_path_for_timeline,
    timeline_slices,
)
from lane_image import make_lane_image
from loader import DEFAULT_EXPORT_ROOT, first_bytes, load_exports

try:
    import numpy as np
except ImportError:
    np = None


DEFAULT_LANE_IMAGE_ROOT = Path(__file__).resolve().parent / "LANE_IMAGES"


def ascii_preview(raw: bytes) -> str:
    return "".join(chr(byte) if 32 <= byte <= 126 else "." for byte in raw)


def array_bytes(array: object) -> bytes:
    data = getattr(array, "data", None)
    if isinstance(data, bytes):
        return data
    if np is not None:
        return np.asarray(array, dtype=np.uint8).reshape(-1).tobytes()
    raise TypeError(f"unsupported array object: {type(array)!r}")


def lane_image_path(root: Path, full_name: str) -> Path:
    return root / f"{full_name.replace('/', '__')}.png"


def main() -> None:
    snapshot_export = load_exports(DEFAULT_EXPORT_ROOT, mmap_mode="r")
    lane_image_root = DEFAULT_LANE_IMAGE_ROOT
    byte_flow_image_root = DEFAULT_BYTE_FLOW_IMAGE_ROOT
    lane_image_root.mkdir(parents=True, exist_ok=True)
    byte_flow_image_root.mkdir(parents=True, exist_ok=True)

    print(f"Loaded: {snapshot_export.root}")
    print(f"Lane images: {lane_image_root}")
    print(f"Byte flow images: {byte_flow_image_root}")
    print()

    lane_image_count = 0
    for snapshot_array in snapshot_export.iter_arrays():
        raw = first_bytes(snapshot_array.data, 32)
        ascii_text = ascii_preview(raw)
        hex_text = raw.hex().upper()
        shape_text = "x".join(str(value) for value in snapshot_array.shape)
        print(f"{snapshot_array.full_name} [{shape_text}]")
        print(f"  first32: {ascii_text}")
        print(f"  hex:     {hex_text}")

        if "lane" in snapshot_array.array_name:
            image = make_lane_image(array_bytes(snapshot_array.data), changed=False)
            image.save(lane_image_path(lane_image_root, snapshot_array.full_name))
            lane_image_count += 1

    print()
    print(f"Generated {lane_image_count} lane images.")

    byte_flow_count = 0
    for timeline_name in snapshot_export.timelines:
        slices = timeline_slices(snapshot_export.root, timeline_name)
        image = make_byte_flow_image(slices, save_slice_images=True)
        output_path = output_path_for_timeline(timeline_name, byte_flow_image_root)
        image.save(output_path)
        byte_flow_count += 1
        print(f"Generated byte flow image: {output_path}")

    print(f"Generated {byte_flow_count} byte flow images.")


if __name__ == "__main__":
    main()
