#!/bin/bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${ROOT_DIR}"

PASSWORD_TEXT="${1:-a}"
OUTPUT_ROOT="${2:-${ROOT_DIR}/in_place_32blk_runs}"

MAX_FAIL="${MAX_FAIL:-0}"
MAX_VERY_SUSPICIOUS="${MAX_VERY_SUSPICIOUS:-1000}"
MAX_SUSPICIOUS="${MAX_SUSPICIOUS:-0}"
MAX_MILDLY_SUSPICIOUS="${MAX_MILDLY_SUSPICIOUS:-999999}"
MAX_UNUSUAL="${MAX_UNUSUAL:-999999}"
MAX_ATTEMPTS="${MAX_ATTEMPTS:-3}"
RETRY_NO_REPORT_DELAY_SEC="${RETRY_NO_REPORT_DELAY_SEC:-1.5}"

env \
  MAX_FAIL="${MAX_FAIL}" \
  MAX_VERY_SUSPICIOUS="${MAX_VERY_SUSPICIOUS}" \
  MAX_SUSPICIOUS="${MAX_SUSPICIOUS}" \
  MAX_MILDLY_SUSPICIOUS="${MAX_MILDLY_SUSPICIOUS}" \
  MAX_UNUSUAL="${MAX_UNUSUAL}" \
  MAX_ATTEMPTS="${MAX_ATTEMPTS}" \
  RETRY_NO_REPORT_DELAY_SEC="${RETRY_NO_REPORT_DELAY_SEC}" \
  bash "${ROOT_DIR}/run_practrand_candidate_once.sh" \
  "${PASSWORD_TEXT}" \
  "32blk" \
  "${OUTPUT_ROOT}"
